// default package
// Generated 08-feb-2015 19:33:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseId generated by hbm2java
 */
@Embeddable
public class CourseId implements java.io.Serializable {

	private String name;
	private String assignedTeacher;

	public CourseId() {
	}

	public CourseId(String name, String assignedTeacher) {
		this.name = name;
		this.assignedTeacher = assignedTeacher;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "assigned_teacher", nullable = false, length = 45)
	public String getAssignedTeacher() {
		return this.assignedTeacher;
	}

	public void setAssignedTeacher(String assignedTeacher) {
		this.assignedTeacher = assignedTeacher;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseId))
			return false;
		CourseId castOther = (CourseId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& ((this.getAssignedTeacher() == castOther.getAssignedTeacher()) || (this.getAssignedTeacher() != null
						&& castOther.getAssignedTeacher() != null && this.getAssignedTeacher().equals(castOther.getAssignedTeacher())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getAssignedTeacher() == null ? 0 : this.getAssignedTeacher().hashCode());
		return result;
	}

}
