// default package
// Generated 08-feb-2015 19:33:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name = "score", catalog = "highschool")
public class Score implements java.io.Serializable {

	private ScoreId id;

	public Score() {
	}

	public Score(ScoreId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "student", column = @Column(name = "student", nullable = false, length = 45)),
			@AttributeOverride(name = "note1", column = @Column(name = "note1", nullable = false)),
			@AttributeOverride(name = "note2", column = @Column(name = "note2", nullable = false)),
			@AttributeOverride(name = "note3", column = @Column(name = "note3", nullable = false)),
			@AttributeOverride(name = "finalNote", column = @Column(name = "final_note", nullable = false)),
			@AttributeOverride(name = "registration", column = @Column(name = "registration", nullable = false)),
			@AttributeOverride(name = "course", column = @Column(name = "course", nullable = false, length = 45)) })
	public ScoreId getId() {
		return this.id;
	}

	public void setId(ScoreId id) {
		this.id = id;
	}

}
