// default package
// Generated 08-feb-2015 19:33:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScoreId generated by hbm2java
 */
@Embeddable
public class ScoreId implements java.io.Serializable {

	private String student;
	private int note1;
	private int note2;
	private int note3;
	private int finalNote;
	private int registration;
	private String course;

	public ScoreId() {
	}

	public ScoreId(String student, int note1, int note2, int note3, int finalNote, int registration, String course) {
		this.student = student;
		this.note1 = note1;
		this.note2 = note2;
		this.note3 = note3;
		this.finalNote = finalNote;
		this.registration = registration;
		this.course = course;
	}

	@Column(name = "student", nullable = false, length = 45)
	public String getStudent() {
		return this.student;
	}

	public void setStudent(String student) {
		this.student = student;
	}

	@Column(name = "note1", nullable = false)
	public int getNote1() {
		return this.note1;
	}

	public void setNote1(int note1) {
		this.note1 = note1;
	}

	@Column(name = "note2", nullable = false)
	public int getNote2() {
		return this.note2;
	}

	public void setNote2(int note2) {
		this.note2 = note2;
	}

	@Column(name = "note3", nullable = false)
	public int getNote3() {
		return this.note3;
	}

	public void setNote3(int note3) {
		this.note3 = note3;
	}

	@Column(name = "final_note", nullable = false)
	public int getFinalNote() {
		return this.finalNote;
	}

	public void setFinalNote(int finalNote) {
		this.finalNote = finalNote;
	}

	@Column(name = "registration", nullable = false)
	public int getRegistration() {
		return this.registration;
	}

	public void setRegistration(int registration) {
		this.registration = registration;
	}

	@Column(name = "course", nullable = false, length = 45)
	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScoreId))
			return false;
		ScoreId castOther = (ScoreId) other;

		return ((this.getStudent() == castOther.getStudent()) || (this.getStudent() != null && castOther.getStudent() != null && this
				.getStudent().equals(castOther.getStudent())))
				&& (this.getNote1() == castOther.getNote1())
				&& (this.getNote2() == castOther.getNote2())
				&& (this.getNote3() == castOther.getNote3())
				&& (this.getFinalNote() == castOther.getFinalNote())
				&& (this.getRegistration() == castOther.getRegistration())
				&& ((this.getCourse() == castOther.getCourse()) || (this.getCourse() != null && castOther.getCourse() != null && this
						.getCourse().equals(castOther.getCourse())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStudent() == null ? 0 : this.getStudent().hashCode());
		result = 37 * result + this.getNote1();
		result = 37 * result + this.getNote2();
		result = 37 * result + this.getNote3();
		result = 37 * result + this.getFinalNote();
		result = 37 * result + this.getRegistration();
		result = 37 * result + (getCourse() == null ? 0 : this.getCourse().hashCode());
		return result;
	}

}
