// default package
// Generated 08-feb-2015 19:33:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "highschool")
public class Student implements java.io.Serializable {

	private String lastName;
	private String firstName;
	private int registrationNumber;
	private int dateOfBirth;
	private Set<Course> courses = new HashSet<Course>(0);

	public Student() {
	}

	public Student(String lastName, String firstName, int registrationNumber, int dateOfBirth) {
		this.lastName = lastName;
		this.firstName = firstName;
		this.registrationNumber = registrationNumber;
		this.dateOfBirth = dateOfBirth;
	}

	public Student(String lastName, String firstName, int registrationNumber, int dateOfBirth, Set<Course> courses) {
		this.lastName = lastName;
		this.firstName = firstName;
		this.registrationNumber = registrationNumber;
		this.dateOfBirth = dateOfBirth;
		this.courses = courses;
	}

	@Id
	@Column(name = "last_name", unique = true, nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "registration_number", nullable = false)
	public int getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(int registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	@Column(name = "date_of_birth", nullable = false)
	public int getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(int dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "student_has_course", catalog = "highschool", joinColumns = { @JoinColumn(name = "student_last_name", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "course_name", nullable = false, updatable = false) })
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
