// default package
// Generated 08-feb-2015 19:33:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "highschool")
public class Teacher implements java.io.Serializable {

	private String lastName;
	private Course course;
	private String firstName;
	private int dateOfBirth;

	public Teacher() {
	}

	public Teacher(Course course, String firstName, int dateOfBirth) {
		this.course = course;
		this.firstName = firstName;
		this.dateOfBirth = dateOfBirth;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "course"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "last_name", unique = true, nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "date_of_birth", nullable = false)
	public int getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(int dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

}
